export default [
  {
    kmpl: 13.5,
    highway_kmpl: 16.2,
    category: "compact",
    transmission: "manual",
    fuel_type: "flex",
    manufacturer: "Fiat",
    model: "Mobi",
    year: 2023,
    rental_factor: 0.86, // Valor de venda dividido por 50.000
  },
  {
    kmpl: 12.9,
    highway_kmpl: 15.7,
    category: "compact",
    transmission: "automatic",
    fuel_type: "flex",
    manufacturer: "Chevrolet",
    model: "Onix",
    year: 2023,
    rental_factor: 1.07,
  },
  {
    kmpl: 12.4,
    highway_kmpl: 14.8,
    category: "compact",
    transmission: "manual",
    fuel_type: "flex",
    manufacturer: "Volkswagen",
    model: "Gol",
    year: 2023,
    rental_factor: 0.98,
  },
  {
    kmpl: 14.2,
    highway_kmpl: 16.9,
    category: "compact",
    transmission: "manual",
    fuel_type: "flex",
    manufacturer: "Renault",
    model: "Kwid",
    year: 2023,
    rental_factor: 0.849,
  },
  {
    kmpl: 13.2,
    highway_kmpl: 15.6,
    category: "compact",
    transmission: "manual",
    fuel_type: "flex",
    manufacturer: "Ford",
    model: "Ka",
    year: 2023,
    rental_factor: 0.96,
  },
  {
    kmpl: 12.7,
    highway_kmpl: 15.0,
    category: "compact",
    transmission: "manual",
    fuel_type: "flex",
    manufacturer: "Toyota",
    model: "Etios",
    year: 2023,
    rental_factor: 1.041,
  },
  {
    kmpl: 12.3,
    highway_kmpl: 14.5,
    category: "compact",
    transmission: "automatic",
    fuel_type: "flex",
    manufacturer: "Hyundai",
    model: "HB20",
    year: 2023,
    rental_factor: 1.12,
  },
  {
    kmpl: 12.6,
    highway_kmpl: 15.2,
    category: "compact",
    transmission: "automatic",
    fuel_type: "flex",
    manufacturer: "Nissan",
    model: "Versa",
    year: 2023,
    rental_factor: 1.23,
  },
  {
    kmpl: 12.8,
    highway_kmpl: 15.4,
    category: "compact",
    transmission: "automatic",
    fuel_type: "flex",
    manufacturer: "Honda",
    model: "Fit",
    year: 2023,
    rental_factor: 1.34,
  },
  {
    kmpl: 12.1,
    highway_kmpl: 14.2,
    category: "sedan",
    transmission: "automatic",
    fuel_type: "flex",
    manufacturer: "Chevrolet",
    model: "Cruze",
    year: 2023,
    rental_factor: 1.85,
  },
  {
    kmpl: 11.9,
    highway_kmpl: 14.1,
    category: "sedan",
    transmission: "automatic",
    fuel_type: "flex",
    manufacturer: "Volkswagen",
    model: "Virtus",
    year: 2023,
    rental_factor: 1.76,
  },
  {
    kmpl: 12.3,
    highway_kmpl: 14.6,
    category: "sedan",
    transmission: "automatic",
    fuel_type: "flex",
    manufacturer: "Toyota",
    model: "Corolla",
    year: 2023,
    rental_factor: 2.07,
  },
  {
    kmpl: 8.7,
    highway_kmpl: 10.4,
    category: "pickup",
    transmission: "automatic",
    fuel_type: "diesel",
    manufacturer: "Ford",
    model: "Ranger",
    year: 2023,
    rental_factor: 3.08,
  },
  {
    kmpl: 10.2,
    highway_kmpl: 12.1,
    category: "SUV",
    transmission: "automatic",
    fuel_type: "flex",
    manufacturer: "Jeep",
    model: "Renegade",
    year: 2023,
    rental_factor: 2.29,
  },
  {
    kmpl: 13.1,
    highway_kmpl: 15.5,
    category: "hatch",
    transmission: "automatic",
    fuel_type: "gas",
    manufacturer: "Audi",
    model: "A3",
    year: 2023,
    rental_factor: 3.0,
  },
  {
    kmpl: 11.8,
    highway_kmpl: 14.0,
    category: "sedan",
    transmission: "automatic",
    fuel_type: "gas",
    manufacturer: "BMW",
    model: "Série 3",
    year: 2023,
    rental_factor: 3.66,
  },
];
